name: Tools CI

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: .compilers
          key: ${{ runner.os }}-compilers-${{ hashFiles('get_compilers.sh') }}
          restore-keys: |
            ${{ runner.os }}-compilers-
      - name: Install compilers
        run: make compilers
      - name: Build
        id: gh_dist
        run: make gh-dist
      - name: Deploy
        if: github.repository_owner == 'compiler-explorer'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: compiler-explorer
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: out/dist-bin
          DEST_DIR: dist/tools/${{ steps.gh_dist.outputs.branch }}
